name: auth-ms-trigger
description: Trigger for auth microservice
github:
  name: auth-microservice
  owner: Nest-Microservices-Curso-FH
  push:
    branch: ^cloud-branch$
autodetect: true
serviceAccount: projects/fh-nest-microservices/serviceAccounts/856186106369-compute@developer.gserviceaccount.com
build:
  options:
    logging: CLOUD_LOGGING_ONLY
  steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image', '.']
  images:
  - 'gcr.io/$PROJECT_ID/my-image'
